package com.mj.time.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Record implements Serializable {
    /**
     * 自增主键
     * 表字段 : t_record.id
     */
    private Integer id;

    /**
     * 描述
     * 表字段 : t_record.description
     */
    private String description;

    /**
     * 用户id，关联用户表
     * 表字段 : t_record.user_id
     */
    private Integer userId;

    /**
     * 标签id，关联标签表
     * 表字段 : t_record.tag_id
     */
    private Integer tagId;

    /**
     * 开始时间
     * 表字段 : t_record.begin_time
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date beginTime;

    /**
     * 结束时间
     * 表字段 : t_record.end_time
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date endTime;

    /**
     * 创建时间
     * 表字段 : t_record.create_time
     */
    private Date createTime;

    /**
     * 更新时间
     * 表字段 : t_record.modify_time
     */
    private Date modifyTime;

    /**
     * 
     * 表字段 : t_record.bak1
     */
    private String bak1;

    /**
     * 
     * 表字段 : t_record.bak2
     */
    private String bak2;

    /**
     * 
     * 表字段 : t_record.bak3
     */
    private String bak3;

    private User user;

    private Tag tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 自增主键 字段:t_record.id
     *
     * @return t_record.id, 自增主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 自增主键 字段:t_record.id
     *
     * @param id the value for t_record.id, 自增主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 描述 字段:t_record.description
     *
     * @return t_record.description, 描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 描述 字段:t_record.description
     *
     * @param description the value for t_record.description, 描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取 用户id，关联用户表 字段:t_record.user_id
     *
     * @return t_record.user_id, 用户id，关联用户表
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置 用户id，关联用户表 字段:t_record.user_id
     *
     * @param userId the value for t_record.user_id, 用户id，关联用户表
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取 标签id，关联标签表 字段:t_record.tag_id
     *
     * @return t_record.tag_id, 标签id，关联标签表
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * 设置 标签id，关联标签表 字段:t_record.tag_id
     *
     * @param tagId the value for t_record.tag_id, 标签id，关联标签表
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * 获取 开始时间 字段:t_record.begin_time
     *
     * @return t_record.begin_time, 开始时间
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * 设置 开始时间 字段:t_record.begin_time
     *
     * @param beginTime the value for t_record.begin_time, 开始时间
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * 获取 结束时间 字段:t_record.end_time
     *
     * @return t_record.end_time, 结束时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * 设置 结束时间 字段:t_record.end_time
     *
     * @param endTime the value for t_record.end_time, 结束时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * 获取 创建时间 字段:t_record.create_time
     *
     * @return t_record.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:t_record.create_time
     *
     * @param createTime the value for t_record.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 更新时间 字段:t_record.modify_time
     *
     * @return t_record.modify_time, 更新时间
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * 设置 更新时间 字段:t_record.modify_time
     *
     * @param modifyTime the value for t_record.modify_time, 更新时间
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * 获取  字段:t_record.bak1
     *
     * @return t_record.bak1, 
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * 设置  字段:t_record.bak1
     *
     * @param bak1 the value for t_record.bak1, 
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * 获取  字段:t_record.bak2
     *
     * @return t_record.bak2, 
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * 设置  字段:t_record.bak2
     *
     * @param bak2 the value for t_record.bak2, 
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * 获取  字段:t_record.bak3
     *
     * @return t_record.bak3, 
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * 设置  字段:t_record.bak3
     *
     * @param bak3 the value for t_record.bak3, 
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user=user;
    }

    public Tag getTag() {
        return tag;
    }

    public void setTag(Tag tag) {
        this.tag=tag;
    }
}