package com.mj.time.domain;

import java.io.Serializable;
import java.util.Date;

public class Tag implements Serializable {
    /**
     * 自增主键
     * 表字段 : t_tag.id
     */
    private Integer id;

    /**
     * 标签名
     * 表字段 : t_tag.name
     */
    private String name;

    /**
     * 标签颜色
     * 表字段 : t_tag.color
     */
    private String color;

    /**
     * 标签类别
     * 表字段 : t_tag.type
     */
    private Byte type;

    /**
     * 创建人
     * 表字段 : t_tag.creator
     */
    private Integer creator;

    /**
     * 创建时间
     * 表字段 : t_tag.create_time
     */
    private Date createTime;

    /**
     * 更新时间
     * 表字段 : t_tag.modify_time
     */
    private Date modifyTime;

    /**
     * 
     * 表字段 : t_tag.bak1
     */
    private String bak1;

    /**
     * 
     * 表字段 : t_tag.bak2
     */
    private String bak2;

    /**
     * 
     * 表字段 : t_tag.bak3
     */
    private String bak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 自增主键 字段:t_tag.id
     *
     * @return t_tag.id, 自增主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 自增主键 字段:t_tag.id
     *
     * @param id the value for t_tag.id, 自增主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 标签名 字段:t_tag.name
     *
     * @return t_tag.name, 标签名
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 标签名 字段:t_tag.name
     *
     * @param name the value for t_tag.name, 标签名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 标签颜色 字段:t_tag.color
     *
     * @return t_tag.color, 标签颜色
     */
    public String getColor() {
        return color;
    }

    /**
     * 设置 标签颜色 字段:t_tag.color
     *
     * @param color the value for t_tag.color, 标签颜色
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * 获取 标签类别 字段:t_tag.type
     *
     * @return t_tag.type, 标签类别
     */
    public Byte getType() {
        return type;
    }

    /**
     * 设置 标签类别 字段:t_tag.type
     *
     * @param type the value for t_tag.type, 标签类别
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * 获取 创建人 字段:t_tag.creator
     *
     * @return t_tag.creator, 创建人
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * 设置 创建人 字段:t_tag.creator
     *
     * @param creator the value for t_tag.creator, 创建人
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * 获取 创建时间 字段:t_tag.create_time
     *
     * @return t_tag.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:t_tag.create_time
     *
     * @param createTime the value for t_tag.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 更新时间 字段:t_tag.modify_time
     *
     * @return t_tag.modify_time, 更新时间
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * 设置 更新时间 字段:t_tag.modify_time
     *
     * @param modifyTime the value for t_tag.modify_time, 更新时间
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * 获取  字段:t_tag.bak1
     *
     * @return t_tag.bak1, 
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * 设置  字段:t_tag.bak1
     *
     * @param bak1 the value for t_tag.bak1, 
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * 获取  字段:t_tag.bak2
     *
     * @return t_tag.bak2, 
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * 设置  字段:t_tag.bak2
     *
     * @param bak2 the value for t_tag.bak2, 
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * 获取  字段:t_tag.bak3
     *
     * @return t_tag.bak3, 
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * 设置  字段:t_tag.bak3
     *
     * @param bak3 the value for t_tag.bak3, 
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}