package com.mj.time.domain;

import java.io.Serializable;
import java.util.Date;

public class Todo implements Serializable {
    /**
     * 自增主键
     * 表字段 : t_todo.id
     */
    private Integer id;

    /**
     * 用户id，关联用户表
     * 表字段 : t_todo.user_id
     */
    private Integer userId;

    /**
     * 标签id，表示类别，关联标签表
     * 表字段 : t_todo.tag_id
     */
    private Integer tagId;

    /**
     * 开始时间
     * 表字段 : t_todo.begin_time
     */
    private Date beginTime;

    /**
     * 结束时间
     * 表字段 : t_todo.end_time
     */
    private Date endTime;

    /**
     * 重要紧急程度
     * 表字段 : t_todo.level
     */
    private String level;

    /**
     * 创建时间
     * 表字段 : t_todo.create_time
     */
    private Date createTime;

    /**
     * 更新时间
     * 表字段 : t_todo.modify_time
     */
    private Date modifyTime;

    /**
     * 内容
     * 表字段 : t_todo.content
     */
    private String content;

    /**
     * 
     * 表字段 : t_todo.bak1
     */
    private String bak1;

    /**
     * 
     * 表字段 : t_todo.bak2
     */
    private String bak2;

    /**
     * 
     * 表字段 : t_todo.bak3
     */
    private String bak3;

    private User user;

    private Tag tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_todo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 自增主键 字段:t_todo.id
     *
     * @return t_todo.id, 自增主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 自增主键 字段:t_todo.id
     *
     * @param id the value for t_todo.id, 自增主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 用户id，关联用户表 字段:t_todo.user_id
     *
     * @return t_todo.user_id, 用户id，关联用户表
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置 用户id，关联用户表 字段:t_todo.user_id
     *
     * @param userId the value for t_todo.user_id, 用户id，关联用户表
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取 标签id，表示类别，关联标签表 字段:t_todo.tag_id
     *
     * @return t_todo.tag_id, 标签id，表示类别，关联标签表
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * 设置 标签id，表示类别，关联标签表 字段:t_todo.tag_id
     *
     * @param tagId the value for t_todo.tag_id, 标签id，表示类别，关联标签表
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * 获取 开始时间 字段:t_todo.begin_time
     *
     * @return t_todo.begin_time, 开始时间
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * 设置 开始时间 字段:t_todo.begin_time
     *
     * @param beginTime the value for t_todo.begin_time, 开始时间
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * 获取 结束时间 字段:t_todo.end_time
     *
     * @return t_todo.end_time, 结束时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * 设置 结束时间 字段:t_todo.end_time
     *
     * @param endTime the value for t_todo.end_time, 结束时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * 获取 重要紧急程度 字段:t_todo.level
     *
     * @return t_todo.level, 重要紧急程度
     */
    public String getLevel() {
        return level;
    }

    /**
     * 设置 重要紧急程度 字段:t_todo.level
     *
     * @param level the value for t_todo.level, 重要紧急程度
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * 获取 创建时间 字段:t_todo.create_time
     *
     * @return t_todo.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:t_todo.create_time
     *
     * @param createTime the value for t_todo.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取 更新时间 字段:t_todo.modify_time
     *
     * @return t_todo.modify_time, 更新时间
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * 设置 更新时间 字段:t_todo.modify_time
     *
     * @param modifyTime the value for t_todo.modify_time, 更新时间
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * 获取 内容 字段:t_todo.content
     *
     * @return t_todo.content, 内容
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置 内容 字段:t_todo.content
     *
     * @param content the value for t_todo.content, 内容
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * 获取  字段:t_todo.bak1
     *
     * @return t_todo.bak1, 
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * 设置  字段:t_todo.bak1
     *
     * @param bak1 the value for t_todo.bak1, 
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * 获取  字段:t_todo.bak2
     *
     * @return t_todo.bak2, 
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * 设置  字段:t_todo.bak2
     *
     * @param bak2 the value for t_todo.bak2, 
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * 获取  字段:t_todo.bak3
     *
     * @return t_todo.bak3, 
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * 设置  字段:t_todo.bak3
     *
     * @param bak3 the value for t_todo.bak3, 
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user=user;
    }

    public Tag getTag() {
        return tag;
    }

    public void setTag(Tag tag) {
        this.tag=tag;
    }
}