spring:
  datasource:
    url: jdbc:mysql://47.105.163.206:3306/order_staging?characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: vinson
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver